name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: typst-community/setup-typst@v3
      - name: Run
        run: |
          ./setup-font.sh
          ./compile.sh
      - name: Upload Build files
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            ./build
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "./build/*"